### ISSUE TITLE
Create Dockerfiles for Project

### ISSUE THREAD

**Issue by virendracarpenter** [DjangoCRM/django-crm#12]
Create Dockerfiles for the project to facilitate containerization and deployment.

Additional Notes:
 * Please specify any base images, required dependencies, or specific build instructions.
 * Consider using multi-stage builds for optimized image size.
 * Test the Dockerfiles thoroughly to ensure correct image creation and functionality.
By creating Dockerfiles, we can streamline the development, testing, and deployment processes.

**Comment by DjangoCRM** [comment]
I'm not sure what I should say. I don't use Docker. And I was going to figure it out for this project later. So please be patient.

**Comment by DjangoCRM** [comment]
Hi! Thank you for your patience.
I published the first issue #16  as a task in which you can participate.
Please have a look.

**Comment by mishrasiddhant001** [comment]
@DjangoCRM can you assign it to me. I can dockerize it,

**Comment by DjangoCRM** [comment]
@mishrasiddhant001   There is #13 pull request that needs review.
