### ISSUE TITLE
installation go wrong whitout LOAD_EXCHANGE_RATE

### ISSUE THREAD

**Issue by buoncri** [DjangoCRM/django-crm#4]
Hi and thanks for the code :-D

installation_and_configuration_guide.md, haveing crash in doing ```Manage.py collectstatic```.

```
File "/home/luca/tmp/django-crm/crm/utils/rates_loader.py", line 17, in <module> 
BACKEND = import_string(settings.LOAD_RATE_BACKEND)
...
ModuleNotFoundError: No module named 'crm.backends.<specify_backend>'
```

Thiis, while ```LOAD_EXCHANGE_RATE = False```. Is there a way to not use only the "RATE_BACKEND" and go on ?

**Comment by DjangoCRM** [comment]
Hi! You are welcome )

Let me take a look and fix this.
In the meantime, skip collectstatic. It needs to be run only on a production server.
You can start a development server:

```
python manage.py runserver 
```

**Comment by DjangoCRM** [comment]
Have you updated your project from this repository before?
Did you run `runserver`  command after following the previous steps as instructed in the [guide](../blob/main/docs/installation_and_configuration_guide.md) (I have updated it)?
Seems I was not clear. Sorry.

**Comment by DjangoCRM** [comment]
Regarding  a vanilla configuration. I think you are right.
Default settings and instructions were specified for the production server. It's quite strict.
Now the default settings are specified for running on the development server.
For the first start of the project you only need to specify the data for communication with the database. It's not exactly vanilla, but nevertheless )
I've reflected the simplification in the instructions.
Please update your project and do everything according to the instructions.
I did the same thing, step by step. Everything works.
Anyway let me know if something is wrong or not clear.
