### ISSUE TITLE
Update Readme.md to make it more engaging

### ISSUE THREAD

**Issue by QuickHarsh** [DjangoCRM/django-crm#65]
The updated version is more engaging and visually appealing due to the addition of emojis, which help highlight key points and actions.

**Comment by DjangoCRM** [comment]
Sorry. Text matters and cannot be replaced by emoji. By significantly reducing text, important keywords are lost and the meaning conveyed is distorted. You can rewrite existing text to improve it, provide new meaningful texts and of course add a few emojis 😊

**Comment by QuickHarsh** [comment]
i will not change the texts but i will add few emojis on perfect place to make it more engaging!please assign me so i can do that.......
